- name: yum update
  yum : name=* state=latest

- name: Enable amzn2extra-nginx1.12 repository
  shell: amazon-linux-extras install nginx1.12 -y
  changed_when: false

- name: Install Nginx packages from amazon-linux-extras
  yum:
    name: nginx
    state: present