- name: Get Nginx package list from local
  yum:
    disablerepo: "*"
    list: nginx
  register: installed_pkgs

- name: Enable amzn2extra-nginx1 repository if nginx is not installed
  shell: amazon-linux-extras enable nginx1
  when: installed_pkgs.results | length == 0

- name: Install Nginx packages from amazon-linux-extras
  yum:
    name: nginx
    state: present

- name: Start service nginx, if not started
  service:
    name: nginx
    state: started