---
- hosts: target
  become: yes
  tasks: 
    - name: yum update
      yum : name=* state=latest
    - name: install nginx
      yum: name=nginx state=present
    - name: nginx running and enabled
      service: name=nginx state=started enabled=yes