---
- hosts: target
  become: yes
  tasks:
  - name: install epel-release
    yum:
      name: epel-release
     state: present
    sudo: yes
    
  - name: install nginx
    yum: name=nginx state=present
  - name: nginx running and enabled
    service: name=nginx state=started enabled=yes

