---
- name: Cloning rbenv from git
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Cloning rbenv build plugin from git
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/root/.rbenv/plugins/ruby
